# Generated by Django 2.2 on 2020-11-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201107_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
